"""Initial migration

Revision ID: 25965703f301
Revises: 5834bd9e45c4
Create Date: 2025-11-29 13:23:47.184148

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '25965703f301'
down_revision = '5834bd9e45c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_methods')
    with op.batch_alter_table('meilisearch_product_sync', schema=None) as batch_op:
        batch_op.drop_index('idx_product_sync_product')
        batch_op.drop_index('idx_product_sync_status')

    op.drop_table('meilisearch_product_sync')
    op.drop_table('newsletters')
    op.drop_table('shipping_zones')
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.drop_index('ix_inventory_product_id')
        batch_op.drop_index('ix_inventory_variant_id')

    op.drop_table('inventory')
    op.drop_table('notification_preferences')
    op.drop_table('theme_settings')
    with op.batch_alter_table('meilisearch_sync_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_meilisearch_sync_logs_document_id')
        batch_op.drop_index('ix_meilisearch_sync_logs_index_name')

    op.drop_table('meilisearch_sync_logs')
    op.drop_table('cart_items')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index('ix_categories_parent_id')
        batch_op.drop_index('ix_categories_slug')

    op.drop_table('categories')
    op.drop_table('verification_codes')
    op.drop_table('meilisearch_search_logs')
    op.drop_table('orders')
    op.drop_table('order_attachments')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('idx_user_read_created')
        batch_op.drop_index('idx_user_type')
        batch_op.drop_index('ix_notifications_created_at')
        batch_op.drop_index('ix_notifications_read')
        batch_op.drop_index('ix_notifications_user_id')

    op.drop_table('notifications')
    op.drop_table('reviews')
    with op.batch_alter_table('token_blacklist', schema=None) as batch_op:
        batch_op.drop_index('ix_token_blacklist_jti')

    op.drop_table('token_blacklist')
    op.drop_table('addresses')
    with op.batch_alter_table('pesapal_transactions', schema=None) as batch_op:
        batch_op.drop_index('idx_pesapal_created_at')
        batch_op.drop_index('idx_pesapal_email')
        batch_op.drop_index('idx_pesapal_merchant_ref')
        batch_op.drop_index('idx_pesapal_order_status')
        batch_op.drop_index('idx_pesapal_tracking_id')
        batch_op.drop_index('idx_pesapal_user_status')

    op.drop_table('pesapal_transactions')
    op.drop_table('coupons')
    with op.batch_alter_table('search_log', schema=None) as batch_op:
        batch_op.drop_index('idx_search_log_created')
        batch_op.drop_index('idx_search_log_query')
        batch_op.drop_index('idx_search_log_session')
        batch_op.drop_index('idx_search_log_user')

    op.drop_table('search_log')
    with op.batch_alter_table('topbar_slides', schema=None) as batch_op:
        batch_op.drop_index('ix_topbar_slides_is_active')
        batch_op.drop_index('ix_topbar_slides_sort_order')

    op.drop_table('topbar_slides')
    with op.batch_alter_table('product_embeddings', schema=None) as batch_op:
        batch_op.drop_index('ix_product_embeddings_product_id')

    op.drop_table('product_embeddings')
    op.drop_table('payment_transactions')
    op.drop_table('payments')
    with op.batch_alter_table('mpesa_transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_mpesa_transactions_account_reference')
        batch_op.drop_index('ix_mpesa_transactions_checkout_request_id')
        batch_op.drop_index('ix_mpesa_transactions_idempotency_key')
        batch_op.drop_index('ix_mpesa_transactions_merchant_request_id')
        batch_op.drop_index('ix_mpesa_transactions_mpesa_receipt_number')
        batch_op.drop_index('ix_mpesa_transactions_order_id')
        batch_op.drop_index('ix_mpesa_transactions_transaction_id')

    op.drop_table('mpesa_transactions')
    with op.batch_alter_table('admin_activity_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_admin_activity_logs_created_at')

    op.drop_table('admin_activity_logs')
    op.drop_table('products')
    with op.batch_alter_table('carousel_banners', schema=None) as batch_op:
        batch_op.drop_index('ix_carousel_banners_is_active')
        batch_op.drop_index('ix_carousel_banners_name')
        batch_op.drop_index('ix_carousel_banners_position')
        batch_op.drop_index('ix_carousel_banners_sort_order')

    op.drop_table('carousel_banners')
    with op.batch_alter_table('search_suggestion', schema=None) as batch_op:
        batch_op.drop_index('idx_suggestion_count')
        batch_op.drop_index('idx_suggestion_term')

    op.drop_table('search_suggestion')
    op.drop_table('wishlist_items')
    op.drop_table('meilisearch_config')
    op.drop_table('theme_presets')
    op.drop_table('promotions')
    op.drop_table('brands')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_email')

    op.drop_table('users')
    with op.batch_alter_table('search_analytics_daily', schema=None) as batch_op:
        batch_op.drop_index('idx_analytics_date')

    op.drop_table('search_analytics_daily')
    op.drop_table('product_compatibility')
    with op.batch_alter_table('contact_cta_slides', schema=None) as batch_op:
        batch_op.drop_index('ix_contact_cta_slides_is_active')
        batch_op.drop_index('ix_contact_cta_slides_sort_order')

    op.drop_table('contact_cta_slides')
    with op.batch_alter_table('meilisearch_sync_log', schema=None) as batch_op:
        batch_op.drop_index('idx_sync_log_created')
        batch_op.drop_index('idx_sync_log_status')

    op.drop_table('meilisearch_sync_log')
    op.drop_table('shipping_methods')
    op.drop_table('product_images')
    op.drop_table('product_variants')
    op.drop_table('order_items')
    op.drop_table('footer_settings')
    op.drop_table('admin_mfa')
    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.drop_index('ix_carts_guest_id')

    op.drop_table('carts')
    with op.batch_alter_table('side_panels', schema=None) as batch_op:
        batch_op.drop_index('ix_side_panels_is_active')
        batch_op.drop_index('ix_side_panels_panel_type')
        batch_op.drop_index('ix_side_panels_position')
        batch_op.drop_index('ix_side_panels_sort_order')

    op.drop_table('side_panels')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('side_panels',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('panel_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('position', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('metric', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('icon_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('gradient', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('features', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='side_panels_pkey')
    )
    with op.batch_alter_table('side_panels', schema=None) as batch_op:
        batch_op.create_index('ix_side_panels_sort_order', ['sort_order'], unique=False)
        batch_op.create_index('ix_side_panels_position', ['position'], unique=False)
        batch_op.create_index('ix_side_panels_panel_type', ['panel_type'], unique=False)
        batch_op.create_index('ix_side_panels_is_active', ['is_active'], unique=False)

    op.create_table('carts',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('carts_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('guest_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('subtotal', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('tax', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('shipping', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('discount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('coupon_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('shipping_method_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('payment_method_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('shipping_address_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('billing_address_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('same_as_shipping', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('requires_shipping', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_activity', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['billing_address_id'], ['addresses.id'], name='carts_billing_address_id_fkey'),
    sa.ForeignKeyConstraint(['payment_method_id'], ['payment_methods.id'], name='carts_payment_method_id_fkey'),
    sa.ForeignKeyConstraint(['shipping_address_id'], ['addresses.id'], name='carts_shipping_address_id_fkey'),
    sa.ForeignKeyConstraint(['shipping_method_id'], ['shipping_methods.id'], name='carts_shipping_method_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='carts_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='carts_pkey'),
    postgresql_ignore_search_path=False
    )
    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.create_index('ix_carts_guest_id', ['guest_id'], unique=False)

    op.create_table('admin_mfa',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('secret_key', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('is_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('backup_codes', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('last_used_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='admin_mfa_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='admin_mfa_pkey'),
    sa.UniqueConstraint('user_id', name='admin_mfa_user_id_key')
    )
    op.create_table('footer_settings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('background_color', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('newsletter_bg_color', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('text_color', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('secondary_text_color', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('accent_color', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('link_color', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('link_hover_color', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('newsletter_title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('newsletter_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('company_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('company_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tagline', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('business_hours', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('facebook_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('instagram_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('twitter_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('youtube_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('tiktok_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('linkedin_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('need_help_links', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('about_links', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('categories', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('useful_links', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('resources_links', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('payment_methods', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('copyright_text', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='footer_settings_pkey')
    )
    op.create_table('order_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('variant_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('total', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='order_items_order_id_fkey'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='order_items_product_id_fkey'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], name='order_items_variant_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='order_items_pkey')
    )
    op.create_table('product_variants',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('product_variants_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('color', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('size', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('sale_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('stock', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sku', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='product_variants_product_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='product_variants_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('product_images',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('original_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('url', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_primary', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('alt_text', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('uploaded_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='product_images_product_id_fkey'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name='product_images_uploaded_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='product_images_pkey')
    )
    op.create_table('shipping_methods',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('shipping_methods_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('shipping_zone_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('min_order_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('max_weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('estimated_days', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['shipping_zone_id'], ['shipping_zones.id'], name='shipping_methods_shipping_zone_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='shipping_methods_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('meilisearch_sync_log',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sync_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('total_products', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('synced_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('failed_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('task_uid', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('duration_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('triggered_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], name='meilisearch_sync_log_triggered_by_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='meilisearch_sync_log_pkey')
    )
    with op.batch_alter_table('meilisearch_sync_log', schema=None) as batch_op:
        batch_op.create_index('idx_sync_log_status', ['status'], unique=False)
        batch_op.create_index('idx_sync_log_created', ['created_at'], unique=False)

    op.create_table('contact_cta_slides',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('subtitle', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('image', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('gradient', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('accent_color', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('icon', sa.VARCHAR(length=255), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='contact_cta_slides_pkey')
    )
    with op.batch_alter_table('contact_cta_slides', schema=None) as batch_op:
        batch_op.create_index('ix_contact_cta_slides_sort_order', ['sort_order'], unique=False)
        batch_op.create_index('ix_contact_cta_slides_is_active', ['is_active'], unique=False)

    op.create_table('product_compatibility',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('incompatible_product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('required_product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_incompatible', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_required', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['incompatible_product_id'], ['products.id'], name='product_compatibility_incompatible_product_id_fkey'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='product_compatibility_product_id_fkey'),
    sa.ForeignKeyConstraint(['required_product_id'], ['products.id'], name='product_compatibility_required_product_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='product_compatibility_pkey')
    )
    op.create_table('search_analytics_daily',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('total_searches', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('unique_queries', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('unique_users', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('zero_result_searches', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('avg_processing_time_ms', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('total_clicks', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('click_through_rate', sa.NUMERIC(precision=5, scale=4), autoincrement=False, nullable=True),
    sa.Column('conversion_rate', sa.NUMERIC(precision=5, scale=4), autoincrement=False, nullable=True),
    sa.Column('top_queries', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('top_zero_result_queries', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='search_analytics_daily_pkey'),
    sa.UniqueConstraint('date', name='search_analytics_daily_date_key')
    )
    with op.batch_alter_table('search_analytics_daily', schema=None) as batch_op:
        batch_op.create_index('idx_analytics_date', ['date'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('users_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('role', postgresql.ENUM('USER', 'ADMIN', 'MODERATOR', name='userrole'), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('address', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('avatar_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_login', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('email_verified', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('phone_verified', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('verification_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('verification_code_expires', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_google_user', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    postgresql_ignore_search_path=False
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_users_email', ['email'], unique=True)

    op.create_table('brands',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('brands_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('logo_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('website', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('is_featured', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='brands_pkey'),
    sa.UniqueConstraint('slug', name='brands_slug_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('promotions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('discount_type', postgresql.ENUM('PERCENTAGE', 'FIXED', name='coupontype'), autoincrement=False, nullable=False),
    sa.Column('discount_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('min_order_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('max_discount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('product_ids', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category_ids', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='promotions_pkey')
    )
    op.create_table('theme_presets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('thumbnail_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('theme_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('is_default', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='theme_presets_pkey')
    )
    op.create_table('meilisearch_config',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('key', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('value', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='meilisearch_config_updated_by_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='meilisearch_config_pkey'),
    sa.UniqueConstraint('key', name='meilisearch_config_key_key')
    )
    op.create_table('wishlist_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='wishlist_items_product_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='wishlist_items_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='wishlist_items_pkey')
    )
    op.create_table('search_suggestion',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('term', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('normalized_term', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('search_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('click_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('conversion_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_searched_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_promoted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_blocked', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name='search_suggestion_category_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='search_suggestion_pkey'),
    sa.UniqueConstraint('normalized_term', name='search_suggestion_normalized_term_key')
    )
    with op.batch_alter_table('search_suggestion', schema=None) as batch_op:
        batch_op.create_index('idx_suggestion_term', ['normalized_term'], unique=False)
        batch_op.create_index('idx_suggestion_count', ['search_count'], unique=False)

    op.create_table('carousel_banners',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('position', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('badge_text', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('discount', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('button_text', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('link_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='carousel_banners_pkey')
    )
    with op.batch_alter_table('carousel_banners', schema=None) as batch_op:
        batch_op.create_index('ix_carousel_banners_sort_order', ['sort_order'], unique=False)
        batch_op.create_index('ix_carousel_banners_position', ['position'], unique=False)
        batch_op.create_index('ix_carousel_banners_name', ['name'], unique=False)
        batch_op.create_index('ix_carousel_banners_is_active', ['is_active'], unique=False)

    op.create_table('products',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('products_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('sale_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('stock', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('stock_quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('brand_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('image_urls', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('thumbnail_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('is_featured', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_new', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_sale', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_flash_sale', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_luxury_deal', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_trending', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_top_pick', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_daily_find', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_new_arrival', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('sku', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('dimensions', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('meta_title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('meta_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('short_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('specifications', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('warranty_info', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('shipping_info', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('availability_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('min_order_quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('max_order_quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('related_products', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('cross_sell_products', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('up_sell_products', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('discount_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('tax_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('tax_class', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('barcode', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('manufacturer', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('country_of_origin', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('is_digital', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('download_link', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('download_expiry_days', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_taxable', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_shippable', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('requires_shipping', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_gift_card', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('gift_card_value', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('is_customizable', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('customization_options', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('seo_keywords', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('canonical_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('condition', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('video_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('is_visible', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_searchable', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_comparable', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_preorder', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('preorder_release_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('preorder_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('badge_text', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('badge_color', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name='products_brand_id_fkey'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name='products_category_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='products_pkey'),
    sa.UniqueConstraint('sku', name='products_sku_key'),
    sa.UniqueConstraint('slug', name='products_slug_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('admin_activity_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('admin_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('details', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('endpoint', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('method', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('status_code', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], name='admin_activity_logs_admin_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='admin_activity_logs_pkey')
    )
    with op.batch_alter_table('admin_activity_logs', schema=None) as batch_op:
        batch_op.create_index('ix_admin_activity_logs_created_at', ['created_at'], unique=False)

    op.create_table('mpesa_transactions',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('order_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('transaction_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('checkout_request_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('merchant_request_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('mpesa_receipt_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('account_reference', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('transaction_desc', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('result_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('result_desc', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('request_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('response_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('processed_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('transaction_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('idempotency_key', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('retry_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('mpesa_response', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('callback_response', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('transaction_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('callback_received_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='mpesa_transactions_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='mpesa_transactions_pkey')
    )
    with op.batch_alter_table('mpesa_transactions', schema=None) as batch_op:
        batch_op.create_index('ix_mpesa_transactions_transaction_id', ['transaction_id'], unique=False)
        batch_op.create_index('ix_mpesa_transactions_order_id', ['order_id'], unique=False)
        batch_op.create_index('ix_mpesa_transactions_mpesa_receipt_number', ['mpesa_receipt_number'], unique=False)
        batch_op.create_index('ix_mpesa_transactions_merchant_request_id', ['merchant_request_id'], unique=False)
        batch_op.create_index('ix_mpesa_transactions_idempotency_key', ['idempotency_key'], unique=True)
        batch_op.create_index('ix_mpesa_transactions_checkout_request_id', ['checkout_request_id'], unique=False)
        batch_op.create_index('ix_mpesa_transactions_account_reference', ['account_reference'], unique=False)

    op.create_table('payments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('payment_method', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('transaction_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('transaction_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='payments_order_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='payments_pkey'),
    sa.UniqueConstraint('transaction_id', name='payments_transaction_id_key')
    )
    op.create_table('payment_transactions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('payment_method_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('transaction_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('reference_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('provider_reference', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('transaction_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['payment_method_id'], ['payment_methods.id'], name='payment_transactions_payment_method_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='payment_transactions_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='payment_transactions_pkey'),
    sa.UniqueConstraint('transaction_id', name='payment_transactions_transaction_id_key')
    )
    op.create_table('product_embeddings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('embedding_vector', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('text_content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('model_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('embedding_dimension', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='product_embeddings_product_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='product_embeddings_pkey'),
    sa.UniqueConstraint('product_id', 'model_name', name='uix_product_embedding_model')
    )
    with op.batch_alter_table('product_embeddings', schema=None) as batch_op:
        batch_op.create_index('ix_product_embeddings_product_id', ['product_id'], unique=False)

    op.create_table('topbar_slides',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('campaign', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('subtext', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('bg_color', sa.VARCHAR(length=7), autoincrement=False, nullable=True),
    sa.Column('product_image_url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('product_alt', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('center_content_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('center_content_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('button_text', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('button_link', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='topbar_slides_pkey')
    )
    with op.batch_alter_table('topbar_slides', schema=None) as batch_op:
        batch_op.create_index('ix_topbar_slides_sort_order', ['sort_order'], unique=False)
        batch_op.create_index('ix_topbar_slides_is_active', ['is_active'], unique=False)

    op.create_table('search_log',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('query', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('normalized_query', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('session_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('results_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('processing_time_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('filters_used', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('sort_used', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('page', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('clicked_product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('clicked_position', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('converted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['clicked_product_id'], ['products.id'], name='search_log_clicked_product_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='search_log_user_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='search_log_pkey')
    )
    with op.batch_alter_table('search_log', schema=None) as batch_op:
        batch_op.create_index('idx_search_log_user', ['user_id'], unique=False)
        batch_op.create_index('idx_search_log_session', ['session_id'], unique=False)
        batch_op.create_index('idx_search_log_query', ['normalized_query'], unique=False)
        batch_op.create_index('idx_search_log_created', ['created_at'], unique=False)

    op.create_table('coupons',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('type', postgresql.ENUM('PERCENTAGE', 'FIXED', name='coupontype'), autoincrement=False, nullable=False),
    sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('min_purchase', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('max_discount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('usage_limit', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('used_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='coupons_pkey'),
    sa.UniqueConstraint('code', name='coupons_code_key')
    )
    op.create_table('pesapal_transactions',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('first_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('pesapal_tracking_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('merchant_reference', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('payment_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('callback_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('notification_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('payment_method', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('card_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('last_four_digits', sa.VARCHAR(length=4), autoincrement=False, nullable=True),
    sa.Column('pesapal_receipt_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('payment_status_description', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('status_code', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('transaction_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('callback_received_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('cancelled_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_status_check', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('idempotency_key', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('retry_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('pesapal_response', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('callback_response', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status_response', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='pesapal_transactions_order_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='pesapal_transactions_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='pesapal_transactions_pkey'),
    sa.UniqueConstraint('idempotency_key', name='pesapal_transactions_idempotency_key_key'),
    sa.UniqueConstraint('merchant_reference', name='pesapal_transactions_merchant_reference_key'),
    sa.UniqueConstraint('pesapal_tracking_id', name='pesapal_transactions_pesapal_tracking_id_key')
    )
    with op.batch_alter_table('pesapal_transactions', schema=None) as batch_op:
        batch_op.create_index('idx_pesapal_user_status', ['user_id', 'status'], unique=False)
        batch_op.create_index('idx_pesapal_tracking_id', ['pesapal_tracking_id'], unique=False)
        batch_op.create_index('idx_pesapal_order_status', ['order_id', 'status'], unique=False)
        batch_op.create_index('idx_pesapal_merchant_ref', ['merchant_reference'], unique=False)
        batch_op.create_index('idx_pesapal_email', ['email'], unique=False)
        batch_op.create_index('idx_pesapal_created_at', ['created_at'], unique=False)

    op.create_table('addresses',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('addresses_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('address_line1', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('address_line2', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('state', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('postal_code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('country', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('alternative_phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('address_type', postgresql.ENUM('SHIPPING', 'BILLING', 'BOTH', name='addresstype'), autoincrement=False, nullable=False),
    sa.Column('is_default', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('additional_info', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='addresses_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='addresses_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('token_blacklist',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('jti', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('token_type', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('revoked_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('reason', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='token_blacklist_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='token_blacklist_pkey')
    )
    with op.batch_alter_table('token_blacklist', schema=None) as batch_op:
        batch_op.create_index('ix_token_blacklist_jti', ['jti'], unique=True)

    op.create_table('reviews',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('images', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_verified_purchase', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='reviews_product_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='reviews_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='reviews_pkey')
    )
    op.create_table('notifications',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('type', postgresql.ENUM('ORDER', 'PAYMENT', 'SHIPPING', 'SYSTEM', 'PROMOTION', 'PRODUCT', 'ANNOUNCEMENT', 'PRODUCT_UPDATE', 'PRICE_CHANGE', 'STOCK_ALERT', name='notificationtype'), autoincrement=False, nullable=False),
    sa.Column('priority', postgresql.ENUM('HIGH', 'MEDIUM', 'NORMAL', 'LOW', name='notificationpriority'), autoincrement=False, nullable=True),
    sa.Column('read', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('link', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('image', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('badge', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('read_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='notifications_order_id_fkey'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='notifications_product_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='notifications_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='notifications_pkey')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('ix_notifications_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_notifications_read', ['read'], unique=False)
        batch_op.create_index('ix_notifications_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_user_type', ['user_id', 'type'], unique=False)
        batch_op.create_index('idx_user_read_created', ['user_id', 'read', 'created_at'], unique=False)

    op.create_table('order_attachments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('original_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('mime_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('attachment_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('uploaded_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_public', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='order_attachments_order_id_fkey'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name='order_attachments_uploaded_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='order_attachments_pkey')
    )
    op.create_table('orders',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('order_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('total_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('subtotal', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('tax_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('shipping_address', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('billing_address', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('payment_method', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('payment_status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('shipping_method', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('shipping_cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('tracking_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_archived', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('archived_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='orders_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='orders_pkey'),
    sa.UniqueConstraint('order_number', name='orders_order_number_key')
    )
    op.create_table('meilisearch_search_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('query', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('results_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='meilisearch_search_logs_pkey')
    )
    op.create_table('verification_codes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('code_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('is_used', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('used_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='verification_codes_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='verification_codes_pkey')
    )
    op.create_table('categories',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('categories_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('banner_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_featured', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('image_data', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('image_filename', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('image_mimetype', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('banner_data', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('banner_filename', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('banner_mimetype', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], name='categories_parent_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='categories_pkey'),
    postgresql_ignore_search_path=False
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index('ix_categories_slug', ['slug'], unique=True)
        batch_op.create_index('ix_categories_parent_id', ['parent_id'], unique=False)

    op.create_table('cart_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cart_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('variant_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], name='cart_items_cart_id_fkey'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='cart_items_product_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='cart_items_user_id_fkey'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], name='cart_items_variant_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='cart_items_pkey')
    )
    op.create_table('meilisearch_sync_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('index_name', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('synced_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='meilisearch_sync_logs_pkey')
    )
    with op.batch_alter_table('meilisearch_sync_logs', schema=None) as batch_op:
        batch_op.create_index('ix_meilisearch_sync_logs_index_name', ['index_name'], unique=False)
        batch_op.create_index('ix_meilisearch_sync_logs_document_id', ['document_id'], unique=False)

    op.create_table('theme_settings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('primary_color', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('primary_light', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('primary_dark', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('secondary_color', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('accent_color', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('background_color', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('card_background', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('surface_color', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('text_primary', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('text_secondary', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('text_on_primary', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('border_color', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('divider_color', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('button_primary_bg', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('button_primary_text', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('button_primary_hover', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('button_secondary_bg', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('button_secondary_text', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('success_color', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('warning_color', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('error_color', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('info_color', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('header_background', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('header_text', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('footer_background', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('footer_text', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('link_color', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('link_hover_color', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('badge_color', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('badge_text', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('nav_background', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('nav_text', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('nav_active', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('carousel_background', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('carousel_overlay_dark', sa.VARCHAR(length=19), autoincrement=False, nullable=False),
    sa.Column('carousel_overlay_light', sa.VARCHAR(length=19), autoincrement=False, nullable=False),
    sa.Column('carousel_badge_bg', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('carousel_badge_text', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='theme_settings_created_by_fkey'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='theme_settings_updated_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='theme_settings_pkey')
    )
    op.create_table('notification_preferences',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('order', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('payment', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('product', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('promotion', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('system', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('announcement', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('product_update', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('price_change', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('stock_alert', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('email_notifications', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('push_notifications', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('sms_notifications', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='notification_preferences_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='notification_preferences_pkey'),
    sa.UniqueConstraint('user_id', name='notification_preferences_user_id_key')
    )
    op.create_table('inventory',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('variant_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('stock_level', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reserved_quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reorder_level', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('low_stock_threshold', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sku', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('last_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='inventory_product_id_fkey'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], name='inventory_variant_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='inventory_pkey'),
    sa.UniqueConstraint('product_id', 'variant_id', name='uix_inventory_product_variant')
    )
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.create_index('ix_inventory_variant_id', ['variant_id'], unique=False)
        batch_op.create_index('ix_inventory_product_id', ['product_id'], unique=False)

    op.create_table('shipping_zones',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('country', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('all_regions', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('available_regions', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('min_order_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='shipping_zones_pkey')
    )
    op.create_table('newsletters',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('is_subscribed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='newsletters_pkey'),
    sa.UniqueConstraint('email', name='newsletters_email_key')
    )
    op.create_table('meilisearch_product_sync',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('last_synced_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('sync_status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('last_error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('retry_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('meilisearch_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='meilisearch_product_sync_product_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='meilisearch_product_sync_pkey'),
    sa.UniqueConstraint('product_id', name='meilisearch_product_sync_product_id_key')
    )
    with op.batch_alter_table('meilisearch_product_sync', schema=None) as batch_op:
        batch_op.create_index('idx_product_sync_status', ['sync_status'], unique=False)
        batch_op.create_index('idx_product_sync_product', ['product_id'], unique=False)

    op.create_table('payment_methods',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('instructions', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('min_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('max_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('countries', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='payment_methods_pkey'),
    sa.UniqueConstraint('code', name='payment_methods_code_key')
    )
    # ### end Alembic commands ###
