"""empty message

Revision ID: 6078b820d67e
Revises:
Create Date: 2025-08-28 18:42:50.268881

"""
try:
    from alembic import op
except Exception:
    # Minimal fallback stub so static analysis or non-migration environments don't error.
    # This stub implements only methods used in this migration file.
    class _OpStub:
        def execute(self, *args, **kwargs):
            return None

        class _Batch:
            def __enter__(self):
                return self

            def __exit__(self, exc_type, exc, tb):
                return False

            def alter_column(self, *args, **kwargs):
                return None

            def create_index(self, *args, **kwargs):
                return None

            def drop_index(self, *args, **kwargs):
                return None

            def add_column(self, *args, **kwargs):
                return None

            def drop_column(self, *args, **kwargs):
                return None

            def create_foreign_key(self, *args, **kwargs):
                return None

            def create_unique_constraint(self, *args, **kwargs):
                return None

            def drop_constraint(self, *args, **kwargs):
                return None

            def f(self, name):
                return name

        def batch_alter_table(self, *args, **kwargs):
            from contextlib import contextmanager
            @contextmanager
            def _ctx():
                yield _OpStub._Batch()
            return _ctx()
    op = _OpStub()

try:
    import sqlalchemy as sa
    from sqlalchemy.dialects import postgresql
except Exception:
    # Lightweight stubs for environments without sqlalchemy; these are not full replacements
    # and exist only to avoid NameError / import issues for editors or tests that only parse the file.
    class _SAType:
        def __init__(self, *args, **kwargs): pass

    class _SaStub:
        INTEGER = _SAType
        Integer = _SAType
        VARCHAR = _SAType
        String = _SAType
        TEXT = _SAType
        Text = _SAType
        JSON = _SAType
        DateTime = _SAType
        Boolean = _SAType
        NUMERIC = _SAType
        Column = lambda *a, **k: None

    sa = _SaStub()

    class postgresql:
        @staticmethod
        def TIMESTAMP(*args, **kwargs):
            return _SAType()

        @staticmethod
        def JSON(*args, **kwargs):
            return _SAType()

        @staticmethod
        def ENUM(*args, **kwargs):
            return _SAType()

# revision identifiers, used by Alembic.
revision = '6078b820d67e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()

    # Helper to check if a column exists in the current DB (Postgres)
    def column_exists(table_name: str, column_name: str) -> bool:
        query = sa.text(
            "SELECT 1 FROM information_schema.columns "
            "WHERE table_name = :table AND column_name = :col LIMIT 1"
        )
        result = bind.execute(query, {"table": table_name, "col": column_name}).fetchone()
        return result is not None

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('search_queries', schema=None) as batch_op:
        # Removed drop_index calls for non-existent indexes
        # batch_op.drop_index('ix_search_queries_session_id')
        # batch_op.drop_index('ix_search_queries_user_id')
        pass

    # make drop operations idempotent
    op.execute("DROP TABLE IF EXISTS search_queries CASCADE")
    op.execute("DROP TABLE IF EXISTS search_performance_metrics CASCADE")

    with op.batch_alter_table('search_trending_topics', schema=None) as batch_op:
        # batch_op.drop_index('ix_search_trending_topics_is_active')
        # batch_op.drop_index('ix_search_trending_topics_search_volume')
        # batch_op.drop_index('ix_search_trending_topics_topic_name')
        # batch_op.drop_index('ix_search_trending_topics_trend_score')
        pass

    # safe drops for tables that may be absent
    op.execute("DROP TABLE IF EXISTS search_trending_topics CASCADE")
    with op.batch_alter_table('search_suggestions', schema=None) as batch_op:
        # batch_op.drop_index('ix_search_suggestions_brand_id')
        # batch_op.drop_index('ix_search_suggestions_category_id')
        # batch_op.drop_index('ix_search_suggestions_search_count')
        # batch_op.drop_index('ix_search_suggestions_suggestion_text')
        pass

    op.execute("DROP TABLE IF EXISTS search_suggestions CASCADE")
    with op.batch_alter_table('search_conversions', schema=None) as batch_op:
        # batch_op.drop_index('ix_search_conversions_search_query_id')
        pass

    op.execute("DROP TABLE IF EXISTS search_conversions CASCADE")
    op.execute("DROP TABLE IF EXISTS order_notes CASCADE")
    op.execute("DROP TABLE IF EXISTS payment_refunds CASCADE")
    with op.batch_alter_table('search_user_profiles', schema=None) as batch_op:
        # batch_op.drop_index('ix_search_user_profiles_session_id')
        # batch_op.drop_index('ix_search_user_profiles_user_id')
        pass

    op.execute("DROP TABLE IF EXISTS search_user_profiles CASCADE")

    with op.batch_alter_table('flutterwave_transactions', schema=None) as batch_op:
        # batch_op.drop_index('ix_flutterwave_transactions_flw_ref')
        # batch_op.drop_index('ix_flutterwave_transactions_transaction_id')
        # batch_op.drop_index('ix_flutterwave_transactions_tx_ref')
        pass

    op.execute("DROP TABLE IF EXISTS flutterwave_transactions CASCADE")

    with op.batch_alter_table('search_clicks', schema=None) as batch_op:
        # batch_op.drop_index('ix_search_clicks_product_id')
        # batch_op.drop_index('ix_search_clicks_search_query_id')
        pass

    op.execute("DROP TABLE IF EXISTS search_clicks CASCADE")
    with op.batch_alter_table('admin_activity_logs', schema=None) as batch_op:
        batch_op.alter_column('admin_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('endpoint',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=True)
        # Idempotent index creation: only create if missing
        op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1
                FROM pg_class c
                JOIN pg_namespace n ON n.oid = c.relnamespace
                WHERE c.relkind = 'i'
                  AND c.relname = 'ix_admin_activity_logs_created_at'
            ) THEN
                CREATE INDEX ix_admin_activity_logs_created_at ON admin_activity_logs (created_at);
            END IF;
        END
        $$;
        """)

    with op.batch_alter_table('admin_mfa', schema=None) as batch_op:
        # Drop 'updated_at' column only if it exists
        op.execute("""
        DO $$
        BEGIN
            IF EXISTS (
                SELECT 1
                FROM information_schema.columns
                WHERE table_name = 'admin_mfa'
                  AND column_name = 'updated_at'
            ) THEN
                ALTER TABLE admin_mfa DROP COLUMN updated_at;
            END IF;
        END
        $$;
        """)

    cols_to_add = []

    if not column_exists('mpesa_transactions', 'user_id'):
        cols_to_add.append(sa.Column('user_id', sa.Integer(), nullable=True))

    if not column_exists('mpesa_transactions', 'order_id'):
        cols_to_add.append(sa.Column('order_id', sa.String(length=100), nullable=True))

    if not column_exists('mpesa_transactions', 'description'):
        cols_to_add.append(sa.Column('description', sa.String(length=255), nullable=True))

    if not column_exists('mpesa_transactions', 'idempotency_key'):
        cols_to_add.append(sa.Column('idempotency_key', sa.String(length=100), nullable=True))

    if not column_exists('mpesa_transactions', 'retry_count'):
        cols_to_add.append(sa.Column('retry_count', sa.Integer(), nullable=True))

    if not column_exists('mpesa_transactions', 'error_message'):
        cols_to_add.append(sa.Column('error_message', sa.Text(), nullable=True))

    if not column_exists('mpesa_transactions', 'mpesa_response'):
        cols_to_add.append(sa.Column('mpesa_response', sa.JSON(), nullable=True))

    if not column_exists('mpesa_transactions', 'callback_response'):
        cols_to_add.append(sa.Column('callback_response', sa.JSON(), nullable=True))

    if not column_exists('mpesa_transactions', 'transaction_date'):
        cols_to_add.append(sa.Column('transaction_date', sa.DateTime(), nullable=True))

    if not column_exists('mpesa_transactions', 'callback_received_at'):
        cols_to_add.append(sa.Column('callback_received_at', sa.DateTime(), nullable=True))

    # Now apply changes only if there are missing columns.
    if cols_to_add:
        with op.batch_alter_table('mpesa_transactions', schema=None) as batch_op:
            for col in cols_to_add:
                batch_op.add_column(col)

    with op.batch_alter_table('order_attachments', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'orders', ['order_id'], ['id'])

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'orders', ['order_id'], ['id'])

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'orders', ['order_id'], ['id'])

    with op.batch_alter_table('pesapal_transactions', schema=None) as batch_op:
        # Guard column additions—only add if missing
        pesapal_cols_to_add = []
        
        if not column_exists('pesapal_transactions', 'card_type'):
            pesapal_cols_to_add.append(sa.Column('card_type', sa.String(length=50), nullable=True))
        if not column_exists('pesapal_transactions', 'last_four_digits'):
            pesapal_cols_to_add.append(sa.Column('last_four_digits', sa.String(length=4), nullable=True))
        if not column_exists('pesapal_transactions', 'pesapal_receipt_number'):
            pesapal_cols_to_add.append(sa.Column('pesapal_receipt_number', sa.String(length=50), nullable=True))
        if not column_exists('pesapal_transactions', 'transaction_date'):
            pesapal_cols_to_add.append(sa.Column('transaction_date', sa.DateTime(), nullable=True))
        if not column_exists('pesapal_transactions', 'callback_received_at'):
            pesapal_cols_to_add.append(sa.Column('callback_received_at', sa.DateTime(), nullable=True))
        if not column_exists('pesapal_transactions', 'expires_at'):
            pesapal_cols_to_add.append(sa.Column('expires_at', sa.DateTime(), nullable=True))
        if not column_exists('pesapal_transactions', 'cancelled_at'):
            pesapal_cols_to_add.append(sa.Column('cancelled_at', sa.DateTime(), nullable=True))
        if not column_exists('pesapal_transactions', 'last_status_check'):
            pesapal_cols_to_add.append(sa.Column('last_status_check', sa.DateTime(), nullable=True))
        if not column_exists('pesapal_transactions', 'idempotency_key'):
            pesapal_cols_to_add.append(sa.Column('idempotency_key', sa.String(length=64), nullable=True))
        if not column_exists('pesapal_transactions', 'retry_count'):
            pesapal_cols_to_add.append(sa.Column('retry_count', sa.Integer(), nullable=True))
        if not column_exists('pesapal_transactions', 'error_message'):
            pesapal_cols_to_add.append(sa.Column('error_message', sa.String(length=500), nullable=True))
        if not column_exists('pesapal_transactions', 'pesapal_response'):
            pesapal_cols_to_add.append(sa.Column('pesapal_response', sa.Text(), nullable=True))
        if not column_exists('pesapal_transactions', 'callback_response'):
            pesapal_cols_to_add.append(sa.Column('callback_response', sa.Text(), nullable=True))
        if not column_exists('pesapal_transactions', 'status_response'):
            pesapal_cols_to_add.append(sa.Column('status_response', sa.Text(), nullable=True))

        # Add missing columns
        for col in pesapal_cols_to_add:
            batch_op.add_column(col)

        # Now handle the alter_column and constraint operations
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=15),
               existing_nullable=True)
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('pesapal_tracking_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('callback_url',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               nullable=False,
               existing_server_default=sa.text("'PENDING'::character varying"))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.drop_index('idx_pesapal_status')
        batch_op.drop_index('ix_pesapal_transactions_merchant_reference')
        batch_op.drop_index('ix_pesapal_transactions_order_tracking_id')
        batch_op.drop_index('ix_pesapal_transactions_pesapal_transaction_id')
        
        batch_op.create_unique_constraint(None, ['merchant_reference'])
        batch_op.create_unique_constraint(None, ['pesapal_tracking_id'])
        batch_op.create_unique_constraint(None, ['idempotency_key'])
        batch_op.drop_column('ipn_data')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('request_data')
        batch_op.drop_column('payment_status')
        batch_op.drop_column('payment_status_reason')
        batch_op.drop_column('payment_status_code')
        batch_op.drop_column('customer_phone')
        batch_op.drop_column('pesapal_merchant_reference')
        batch_op.drop_column('customer_email')
        batch_op.drop_column('transaction_type')
        batch_op.drop_column('payment_status_description')
        batch_op.drop_column('transaction_metadata')
        batch_op.drop_column('order_tracking_id')
        batch_op.drop_column('response_data')
        batch_op.drop_column('confirmation_code')
        batch_op.drop_column('pesapal_transaction_id')
        batch_op.drop_column('payment_account')
        batch_op.drop_column('message')

    with op.batch_alter_table('token_blacklist', schema=None) as batch_op:
        batch_op.alter_column('revoked_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token_blacklist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.alter_column('revoked_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)

    with op.batch_alter_table('pesapal_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('payment_account', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('pesapal_transaction_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('confirmation_code', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('response_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('order_tracking_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('transaction_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('payment_status_description', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('transaction_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('customer_email', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('pesapal_merchant_reference', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('customer_phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('payment_status_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('payment_status_reason', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('payment_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('request_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('ipn_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('ix_pesapal_transactions_pesapal_transaction_id', ['pesapal_transaction_id'], unique=False)
        batch_op.create_index('ix_pesapal_transactions_order_tracking_id', ['order_tracking_id'], unique=False)
        batch_op.create_index('ix_pesapal_transactions_merchant_reference', ['merchant_reference'], unique=False)
        batch_op.create_index('idx_pesapal_status', ['status'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'PENDING'::character varying"))
        batch_op.alter_column('callback_url',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('pesapal_tracking_id',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('last_name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('first_name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('phone_number',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
        batch_op.alter_column('currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
        batch_op.alter_column('amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('status_response')
        batch_op.drop_column('callback_response')
        batch_op.drop_column('pesapal_response')
        batch_op.drop_column('error_message')
        batch_op.drop_column('retry_count')
        batch_op.drop_column('idempotency_key')
        batch_op.drop_column('last_status_check')
        batch_op.drop_column('cancelled_at')
        batch_op.drop_column('expires_at')
        batch_op.drop_column('callback_received_at')
        batch_op.drop_column('transaction_date')
        batch_op.drop_column('pesapal_receipt_number')
        batch_op.drop_column('last_four_digits')
        batch_op.drop_column('card_type')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('order_attachments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('mpesa_transactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_mpesa_transactions_order_id'))
        batch_op.drop_index(batch_op.f('ix_mpesa_transactions_idempotency_key'))
        batch_op.alter_column('id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('callback_received_at')
        batch_op.drop_column('transaction_date')
        batch_op.drop_column('callback_response')
        batch_op.drop_column('mpesa_response')
        batch_op.drop_column('error_message')
        batch_op.drop_column('retry_count')
        batch_op.drop_column('idempotency_key')
        batch_op.drop_column('description')
        batch_op.drop_column('order_id')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('admin_mfa', schema=None) as batch_op:
        # Re-add 'updated_at' column only if missing (keep nullable to avoid data issues)
        op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1
                FROM information_schema.columns
                WHERE table_name = 'admin_mfa'
                  AND column_name = 'updated_at'
            ) THEN
                ALTER TABLE admin_mfa ADD COLUMN updated_at TIMESTAMP;
            END IF;
        END
        $$;
        """)

    with op.batch_alter_table('admin_activity_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_activity_logs_created_at'))
        batch_op.alter_column('endpoint',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('admin_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.create_table('search_clicks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('search_query_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('click_position', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('click_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['search_query_id'], ['search_queries.id'], name='search_clicks_search_query_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='search_clicks_pkey')
    )
    with op.batch_alter_table('search_clicks', schema=None) as batch_op:
        batch_op.create_index('ix_search_clicks_search_query_id', ['search_query_id'], unique=False)
        batch_op.create_index('ix_search_clicks_product_id', ['product_id'], unique=False)

    op.create_table('flutterwave_transactions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('payment_transaction_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('flw_ref', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('tx_ref', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('payment_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('processor_response', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('auth_model', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('card_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('card_country', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('card_issuer', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('first_6digits', sa.VARCHAR(length=6), autoincrement=False, nullable=True),
    sa.Column('last_4digits', sa.VARCHAR(length=4), autoincrement=False, nullable=True),
    sa.Column('customer_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('customer_phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('customer_email', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('charged_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('app_fee', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('merchant_fee', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('initiate_request', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('initiate_response', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('webhook_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('verify_response', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('initiated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('webhook_received_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_verify_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['payment_transaction_id'], ['payment_transactions.id'], name='flutterwave_transactions_payment_transaction_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='flutterwave_transactions_pkey')
    )
    with op.batch_alter_table('flutterwave_transactions', schema=None) as batch_op:
        batch_op.create_index('ix_flutterwave_transactions_tx_ref', ['tx_ref'], unique=False)
        batch_op.create_index('ix_flutterwave_transactions_transaction_id', ['transaction_id'], unique=False)
        batch_op.create_index('ix_flutterwave_transactions_flw_ref', ['flw_ref'], unique=False)

    op.create_table('search_user_profiles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('session_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('_search_patterns', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('_click_patterns', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('_conversion_patterns', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('_preferred_categories', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('_preferred_brands', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('_price_range_preference', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('last_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='search_user_profiles_pkey')
    )
    with op.batch_alter_table('search_user_profiles', schema=None) as batch_op:
        batch_op.create_index('ix_search_user_profiles_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_search_user_profiles_session_id', ['session_id'], unique=False)

    op.create_table('payment_refunds',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('payment_transaction_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('refund_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('provider_refund_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=3), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('PENDING', 'PAID', 'COMPLETED', 'FAILED', 'REFUNDED', name='paymentstatus'), autoincrement=False, nullable=True),
    sa.Column('reason', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('initiated_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('approved_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('provider_response', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('processed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name='payment_refunds_approved_by_fkey'),
    sa.ForeignKeyConstraint(['initiated_by'], ['users.id'], name='payment_refunds_initiated_by_fkey'),
    sa.ForeignKeyConstraint(['payment_transaction_id'], ['payment_transactions.id'], name='payment_refunds_payment_transaction_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='payment_refunds_pkey'),
    sa.UniqueConstraint('refund_id', name='payment_refunds_refund_id_key')
    )
    op.create_table('order_notes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('note_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('is_customer_visible', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='order_notes_created_by_fkey'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='order_notes_order_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='order_notes_pkey')
    )
    op.create_table('search_conversions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('search_query_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('conversion_value', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('conversion_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['search_query_id'], ['search_queries.id'], name='search_conversions_search_query_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='search_conversions_pkey'),
    sa.UniqueConstraint('order_id', name='search_conversions_order_id_key')
    )
    with op.batch_alter_table('search_conversions', schema=None) as batch_op:
        batch_op.create_index('ix_search_conversions_search_query_id', ['search_query_id'], unique=False)

    op.create_table('search_suggestions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('suggestion_text', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('search_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_searched', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('brand_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='search_suggestions_pkey')
    )
    with op.batch_alter_table('search_suggestions', schema=None) as batch_op:
        batch_op.create_index('ix_search_suggestions_suggestion_text', ['suggestion_text'], unique=True)
        batch_op.create_index('ix_search_suggestions_search_count', ['search_count'], unique=False)
        batch_op.create_index('ix_search_suggestions_category_id', ['category_id'], unique=False)
        batch_op.create_index('ix_search_suggestions_brand_id', ['brand_id'], unique=False)

    op.create_table('search_trending_topics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('topic_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('_keywords', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('search_volume', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('trend_score', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('date_detected', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='search_trending_topics_pkey')
    )
    with op.batch_alter_table('search_trending_topics', schema=None) as batch_op:
        batch_op.create_index('ix_search_trending_topics_trend_score', ['trend_score'], unique=False)
        batch_op.create_index('ix_search_trending_topics_topic_name', ['topic_name'], unique=False)
        batch_op.create_index('ix_search_trending_topics_search_volume', ['search_volume'], unique=False)
        batch_op.create_index('ix_search_trending_topics_is_active', ['is_active'], unique=False)

    op.create_table('search_performance_metrics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('total_searches', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('unique_users', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('avg_response_time', sa.NUMERIC(precision=8, scale=3), autoincrement=False, nullable=True),
    sa.Column('zero_results_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('conversion_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_revenue', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='search_performance_metrics_pkey')
    )
    with op.batch_alter_table('search_performance_metrics', schema=None) as batch_op:
        batch_op.create_index('ix_search_performance_metrics_date', ['date'], unique=True)

    op.create_table('search_queries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('query_text', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('session_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('results_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('clicked_product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('_filters_used', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('search_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('response_time_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('converted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='search_queries_pkey')
    )
    with op.batch_alter_table('search_queries', schema=None) as batch_op:
        batch_op.create_index('ix_search_queries_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_search_queries_session_id', ['session_id'], unique=False)
        batch_op.create_index('ix_search_queries_search_time', ['search_time'], unique=False)
        batch_op.create_index('ix_search_queries_query_text', ['query_text'], unique=False)
        batch_op.create_index('ix_search_queries_converted', ['converted'], unique=False)

    # ### end Alembic commands ###
